default:
  image: gradle:8.4-jdk21-graal

stages:          # List of stages for jobs, and their order of execution
  - build
  - release
  - deploy

build-job:       # This job runs in the build stage, which runs first.
  stage: build
  before_script:
    - echo BUILD_JOB_ID=$CI_JOB_ID >> build.env
  variables:
    USES_TESTCONTAINERS: "false"
    DATABASE_DB: test
    DATABASE_USER: test
    DATABASE_PASS: test
  services:
    - name: mariadb:11
      alias: mariadb
      variables:
        MARIADB_RANDOM_ROOT_PASSWORD: "yes"
        MARIADB_DATABASE: $DATABASE_DB
        MARIADB_USER: $DATABASE_USER
        MARIADB_PASSWORD: $DATABASE_PASS
    - name: mysql:8.0-debian
      alias: mysql
      variables:
        MYSQL_RANDOM_ROOT_PASSWORD: "yes"
        MYSQL_DATABASE: $DATABASE_DB
        MYSQL_USER: $DATABASE_USER
        MYSQL_PASSWORD: $DATABASE_PASS
    - name: postgres:16
      alias: postgres
      variables:
        POSTGRES_DB: $DATABASE_DB
        POSTGRES_USER: $DATABASE_USER
        POSTGRES_PASSWORD: $DATABASE_PASS
  script:
    # Would add clean but GitLab checks out the repository
    #  each time which removes the build directory
    - gradle build
  artifacts:
    when: always
    paths:
      - build/libs/*.jar
      - build/test-results/test/TEST-*.xml
    reports:
      dotenv: build.env
      junit: build/test-results/test/TEST-*.xml

deploy-job:      # This job runs in the deploy stage.
  stage: deploy  # It only runs when all jobs in the build stage complete successfully.
  environment: production
  script:
    - gradle installDist

  rules:
    - if: $CI_COMMIT_TAG

release-job:
  stage: release
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  needs:
    - job: build-job
      artifacts: true
  script:
    - echo "Creating release for $CI_COMMIT_TAG"
  release:
    name: '$CI_COMMIT_TITLE'
    description: '$CI_COMMIT_MESSAGE'
    tag_name: '$CI_COMMIT_TAG'
    assets:
      links:
        - name: 'PTD1 Server JAR'
          url: '${CI_PROJECT_URL}/-/jobs/${BUILD_JOB_ID}/artifacts/file/build/libs/PTD1-Server-${CI_COMMIT_TAG}.jar'
  rules:
    - if: $CI_COMMIT_TAG