default:
  image: gradle:8.4-jdk17-graal

stages:          # List of stages for jobs, and their order of execution
  - build
  - release
  - deploy

build-job:       # This job runs in the build stage, which runs first.
  stage: build
  before_script:
    - echo BUILD_JOB_ID=$CI_JOB_ID >> build.env
  script:
    - gradle clean build -x test
  artifacts:
    paths:
      - build/libs/*.jar
    reports:
      dotenv: build.env

test-job:
  stage: build
  variables:
    USES_TESTCONTAINERS: "true"
    DATABASE_DB: test
    DATABASE_USER: test
    DATABASE_PASS: test
  services:
    - name: mariadb:11
      variables:
        MARIADB_RANDOM_ROOT_PASSWORD: yes
        # Couldn't seem to set the variable value
        # As the variable above like $DATABASE_DB
        MARIADB_DATABASE: test
        MARIADB_USER: test
        MARIADB_PASSWORD: test
    - name: mysql:8.0-debian
      variables:
        MYSQL_RANDOM_ROOT_PASSWORD: yes
        MYSQL_DATABASE: test
        MYSQL_USER: test
        MYSQL_PASSWORD: test
    - name: postgres:16
      variables:
        POSTGRES_DB: test
        POSTGRES_USER: test
        POSTGRES_PASSWORD: test
  script:
    - gradle cleanTest test
  artifacts:
    when: always
    paths:
      - "build/test-results/test/TEST-*.xml"
    reports:
      junit: build/test-results/test/TEST-*.xml

deploy-job:      # This job runs in the deploy stage.
  stage: deploy  # It only runs when all jobs in the build stage complete successfully.
  environment: production
  script:
    - mvn deploy -s ci_settings.xml

  rules:
    - if: $CI_COMMIT_TAG

release-job:
  stage: release
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  needs:
    - job: build-job
      artifacts: true
  script:
    - echo "Creating release for $CI_COMMIT_TAG"
  release:
    name: '$CI_COMMIT_TITLE'
    description: '$CI_COMMIT_MESSAGE'
    tag_name: '$CI_COMMIT_TAG'
    assets:
      links:
        - name: 'PTD1 Server JAR'
          url: '${CI_PROJECT_URL}/-/jobs/${BUILD_JOB_ID}/artifacts/file/target/PTD1-Server-${CI_COMMIT_TAG}.jar'
  rules:
    - if: $CI_COMMIT_TAG